Carpool/urls.py
from django.conf.urls import include, url,patterns
from django.contrib import admin
import app
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from os import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^broadcast/', include('broadcast.urls')),
    url(r'^$', app.views.IndexView.as_view()),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url('', include('app.urls')),


]

urlpatterns += patterns('',
        url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),)

# urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

api/urls.py
from django.conf.urls import include, url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [


    url(r'^users/$',views.UserList.as_view(), name='users'),

    url(r'^login/$',views.process_login, name='api_login'),

    url(r'^broadcasts/$',views.BroadcastList.as_view(), name='broadcasts'),
    url(r'^messages/$',views.MessageList.as_view(), name='messages'),
    url(r'^get_user/$',views.UserDetail.as_view(), name='user'),
    url(r'^getdashboard/$',views.DashStuff.as_view(), name='dashstuff'),
    url(r'^addride/$',views.addride, name='addride'),
    url(r'^userrides/$',views.UserVehicles.as_view(), name='userride'),
    url(r'^usershared/$',views.UserSharedVehicles.as_view(), name='usershared'),
    url(r'^requests/$',views.Requests.as_view(), name='requests'),



    # url(r'^upload/$',views.upload_file,name='upload'),
]

urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls'))
]

urlpatterns = format_suffix_patterns(urlpatterns)

app/urls.py
from django.conf.urls import url
from app import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/login/$', views.login_user, name='login_user'),

    url(r'^signup/$', views.CreateUser.as_view(), name='sign_up'),

    url(r'^user/(?P<pk>[0-9]+)/$', views.view_user_id, name='profile'),

    url(r'^profile/(?P<user_id>[a-zA_Z0-9]+)/$', views.view_user_name, name='user-profile'),
    url(r'^user/dashboard/$', views.dashboard, name='dashboard'),
    url(r'^user/dashboard/messages/$', views.messages, name='dashboard_messages'),
    url(r'^user/dashboard/notifications/$', views.notifications, name='dashboard_notifications'),

    url(r'^accounts/profile/$', views.create_profile, name='profile_make'),


    url(r'^user/dashboard/sent/$', views.sent, name='dashboard_sent'),

    url(r'^user/dashboard/junk/$', views.messages_junk, name='dashboard_junk'),
    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/read/$', views.messages_read, name='dashboard_messages_read'),
    url(r'^user/dashboard/sent/(?P<message_id>[0-9]+)/read/$', views.messages_read_sent, name='dashboard_messages_read_sent'),

    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/reply/$', views.messages_reply, name='dashboard_messages_reply'),

    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/forward/$', views.messages_forward, name='dashboard_messages_forward'),

    url(r'^user/dashboard/messages/compose/$', views.messages_compose, name='dashboard_messages_compose'),


    url(r'^accounts/login/$', views.login_user, name='login_user'),
    url(r'^terms/$', views.terms, name='terms'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^ride/(?P<user_id>[0-9]+)/$', views.ride, name='ride'),
    url(r'^ride/$', views.ride, name='ride'),

    url(r'^follow/(?P<followee>[0-9]+)/(?P<follower>[0-9]+)/$',views.do_follow,name='follow'),

    url(r'^user/(?P<pk>[0-9]+)/update-profile/$', views.EditUser.as_view(), name='user_update'),

    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^login/$', views.do_login, name='login'),



    url(r'^user/(?P<user_id>[0-9]+)/add-ride/$', views.vehicle_create, name='add_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/view-rides/$', views.vehicle_view, name='view_rides'),

    url(r'^user/(?P<user_id>[0-9]+)/delete-ride/(?P<vehicle_id>[0-9]+)/$', views.vehicle_delete, name='delete_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/share-ride/(?P<vehicle_id>[0-9]+)/$', views.vehicle_share, name='share_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/view-shared/$', views.vehicle_shared_view, name='view_shared'),

    url(r'^user/(?P<user_id>[0-9]+)/search/$', views.vehicle_search, name='search_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/request/(?P<ride_id>[0-9]+)', views.request_ride, name='request_ride'),

    url(r'^sharing/(?P<vehicle_share_id>[0-9]+)/view/$', views.view_single_ride, name='view_shared_ride'),

    url(r'^ride/(?P<ride_id>[0-9]+)/view/$', views.view_single_vehicle, name='view_shared_vehicle'),

    url(r'^sharing/(?P<user_id>[0-9]+)/delete/(?P<vehicle_share_id>[0-9]+)/$', views.vehicle_share_delete, name='delete_shared_ride'),

    url(r'^requests/(?P<user_id>[0-9]+)/view$', views.requests_driver_view, name='request_driver_view'),
    url(r'^requests/all$',views.all_ride_requests, name='view_ride_requests'),
    url(r'^request/(?P<request_id>[0-9]+)/approve/$', views.request_approve, name='request_driver_approve'),
    url(r'^request/(?P<request_id>[0-9]+)/deny/$', views.request_deny, name='request_driver_deny'),

    # url(r'^requests/(?P<user_id>[0-9]+)/view$', views.requests_driver_view, name='request_driver_view'),

    url(r'^request/(?P<request_id>[0-9]+)/view/$', views.request_view, name='request_view'),

    url(r'^user/(?P<user_id>[0-9]+)/requests/$', views.requests_user_view, name='requests_user_view'),

    url(r'^request/(?P<request_id>[0-9]+)/delete/$', views.request_delete, name='request_delete'),

    url(r'^notification/read/$', views.mark_as_read, name='mark_as_read'),

    url(r'^user/messages/unread/$', views.unread_messages, name='unread_messages'),
    url(r'^user/messages/(?P<message_id>[0-9]+)/delete/$', views.delete_message, name='delete_message'),

    url(r'^user/preferences/$', views.preferences, name='preferences'),

     url(r'^user/preferences/image-update$', views.image_update, name='image_update'),

    url(r'^user/preferences/basic-update$', views.basic_update, name='basic_update'),
    url(r'^user/preferences/user-update$', views.user_update, name='user_update'),
    url(r'^user/preferences/driver-update$', views.driver_update, name='driver_update'),
    url(r'^user/preferences/bio-update$', views.bio_update, name='bio_update'),
    url(r'^user/preferences/app-update$', views.app_update, name='app_update'),
    url(r'^user/preferences/social-update$', views.social_update, name='social_update'),
    url(r'^user/preferences/password-update$', views.password_update, name='password_update'),




]

app/templates/app/request/requester_requests.html
{% extends 'app/user/main_template.html' %}
{% load staticfiles %}

{% block cont-header %}
    <section class="content-header">
        <h1>
           All requested rides <small> - {{ request.user.username }}</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i> Home</a></li>

            <li class="active">View requested rides</li>
        </ol>
    </section>
{% endblock %}

{% block body %}

    <div class="content-wrapper" style="min-height: 1126px;">
        <!-- Content Header (Page header) -->


        <!-- Main content -->
        <section class="content">

            <div class="row">

                {% if all_user_requests %}
                    {% for user_request in all_user_requests %}
                        <div class="col-sm-4 col-lg-3 col-md-3 col-space">
                            <div class="thumbnail">
                                <a href="{{ user_request.get_absolute_url }}">
                                    <img src="{% static 'app/img/request.jpg' %}" class="img-responsive">
                                </a>

                                <div class="caption">
                                    <h3 class="visible-lg"><a class="link-black" href="{{ user_request.get_absolute_url }}">{{ user_request.pick }}&nbsp;&rightarrow;&nbsp;{{ user_request.dest  }}</a></h3>
                                    <h4 class="visible-xs visible-sm visible-md"><a class="link-muted" href="{{ user_request.get_absolute_url }}">{{ user_request.pick }}&nbsp;&rightarrow;&nbsp;{{ user_request.dest  }}</a></h4>


                                    <h4><a href="{{ user_request.ride.get_absolute_url }}">Route: {{ user_request.ride }}</a></h4>

                                    {% if user_request.status == 'approved' %}
                                        <p class="ride-people">
                                            <a  class="tooltip-link " data-original-title="status"
                                                data-toggle="tooltip" style="color: green">
                                                <i class="fa fa-user" ></i>&nbsp;{{ user_request.status }}

                                            </a>
                                        </p><!-- end .ride-people -->
                                    {% elif user_request.status == 'denied' %}
                                        <p class="ride-people">
                                            <a  class="tooltip-link " data-original-title="status"
                                                data-toggle="tooltip" style="color: red">
                                                <i class="fa fa-user" ></i>&nbsp;{{ user_request.status }}

                                            </a>
                                        </p><!-- end .ride-people -->
                                    {% else %}
                                        <p class="ride-people">
                                            <a  class="tooltip-link " data-original-title="status"
                                                data-toggle="tooltip" style="color: black">
                                                <i class="fa fa-user" ></i>&nbsp;{{ user_request.status }}

                                            </a>
                                        </p><!-- end .ride-people -->
                                    {% endif %}


                                {% if user_request.status != 'canceled' and not user_request.ride.ended  %}
                                    <form action="{% url 'app:request_delete' user_request.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}

                                        <button type="submit" class="btn btn-danger btn-sm panel-button">
                                            <span class="fa fa-close "></span>
                                        </button>
                                    </form>
                                {% endif %}
                                    <a href="{{ user_request.get_absolute_url }}" class="btn btn-success btn-sm" role="button"
                                       >
                                            <span class="glyphicon glyphicon-eye-open"></span>
                                    </a>

                                </div>
                            </div>
                            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                        </div>
                        {% cycle '' ''  '' '<div class="clearfix hidden-xs hidden-sm"></div>' %}
                        {% cycle '' '' '<div class="clearfix visible-sm"></div>' %}

                    {% endfor %}

                {% else %}
                    <div class="col-sm-12">
                        <br>
                        <a href="{% url 'app:search_ride' request.user.id %} ">
                            <button type="button" class="btn btn-success">
                                <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a request
                            </button>
                        </a>
                    </div>
                {% endif %}
            </div>
        </section>

    </div>

{% endblock %}

app/templates/app/request/requests_view.html
{% extends 'app/user/main_template.html' %}
{% load staticfiles %}
{% load humanize %}

{% block cont-header %}
    <section class="content-header">
        <h1>
            Request <small> - {{ info }}</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i> Home</a></li>
            <li><a href="{% url 'app:view_shared' request.user.id %}"><i class="fa fa-cab"></i> Shared Rides</a></li>

            <li class="active">Ride Requests</li>
        </ol>
    </section>
{% endblock %}
{% block body %}
    <style>
        .ride-box
        {
            -webkit-transition: all  0.4s ease-in-out 0s;
            -moz-transition: all  0.4s ease-in-out 0s;
            -ms-transition: all  0.4s ease-in-out 0s;
            -o-transition: all  0.4s ease-in-out 0s;
            transition: all  0.4s ease-in-out 0s;
            border: 3px solid #000;
            padding: 20px 26px;
            margin: -3px 0 0 0;
            position: relative;
        }
        .ride-box .article-meta li
        {
            display: block
        }
        .ride-box ul.article-meta
        {
            display: inline-block;
            margin: 0;
        }
        .article-content
        {
            display: inline-block;
            margin: 1em 0 0 0;
        }
        .ride-content
        {
            display: inline-block
        }
        .ride-content h3
        {
            display: inline;
            margin: 0 0.5em 0 0;
        }
        .ride-content h3 a
        {
            color: #1f2f3f
        }
        ul.full-ride-meta
        {
            float: right;
            margin: 0;
            list-style: none;
        }
        .ride-box .ride-meta
        {
            margin: 0
        }
        .ride-meta
        {
            margin: 0 0 1.5em 0;
            font-size: 13px;
            float: right;
            color: #a6a497;
        }
        ul.ride-meta li
        {
            display: inline-block;
            margin-right: 1.5em;
        }
        ul.ride-meta li:last-child
        {
            margin: 0
        }
        .ride-box:hover
        {
            background: #f4f1e3;
        }
        /* === Blog rides === */
        .article
        {
            margin-bottom: 3em
        }
        .article:last-of-type
        {
            margin: 0
        }
        .article .ride-image img
        {
            width: 100%;
            border: 3px solid #f4f1e3;
        }
        .article header
        {
            position: relative
        }
        .article-title
        {
            background: #f4f1e3;
            position: absolute;
            bottom: 30px;
            left: 0;
            padding: 1em 2em;
            position: absolute;
        }
        ul.article-meta
        {
            font-size: 13px;
            margin: 1.5em 0 0;
            list-style: none;
            text-transform: capitalize;
        }
        .article-meta li
        {
            display: inline-block;
            margin-right: 1.5em;
        }
        /* === Single ride === */
        .single-article
        {
            margin-bottom: 2em
        }
        .single-article-title h2
        {
            display: inline-block;
            margin: 0;
        }
        .single-article .ride-meta
        {
            margin-top: 1em
        }
        /* === Comments === */
        #comments ol
        {
            list-style: none;
            margin: 0;
        }
        .commentslist ul
        {
            list-style: none
        }
        .comments-area h3
        {
            margin: 0;
            padding: 2em 0;
            text-transform: uppercase;
        }

    </style>
    <div class="content" >
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-header with-border">
                    <i class="fa fa-warning"></i>

                    <h3 class="box-title">Requests</h3>
                </div>
                <!-- /.box-header -->
                {% for pass_request in pass_requests %}
                <div class="box-body">
                    <div class="callout callout-info">
                        <h4><i class="icon fa fa-ticket"></i>&nbsp;{{ pass_request.user|capfirst }}&nbsp;-&nbsp;{{ pass_request.reg_date|naturaltime }}
                            <a class="link-danger text-right" style="float: right;text-decoration: blink" href="{{ pass_request.get_absolute_url }}">more info <i class="fa fa-arrow-circle-right"></i></a> </h4>



                                <span  class="tooltip-link" data-original-title="Source to Destination"
                                    data-toggle="tooltip">
                                    <i class="fa fa-location-arrow"></i>
                                    from {{ pass_request.pick }} to  {{ pass_request.dest }}
                                </span>

                    &nbsp;-&nbsp;

                            {% if pass_request.status == 'approved' %}

                                    <span  class="tooltip-link " data-original-title="status"
                                        data-toggle="tooltip" style="color: green">
                                        <i class="fa fa-user" ></i>&nbsp;{{ pass_request.status }}

                                    </span>

                            {% elif pass_request.status == 'denied' %}

                                    <span  class="tooltip-link " data-original-title="status"
                                        data-toggle="tooltip" style="color: red">
                                        <i class="fa fa-user" ></i>&nbsp;{{ pass_request.status }}

                                    </span>
                            {% else %}

                                    <span  class="tooltip-link " data-original-title="status"
                                        data-toggle="tooltip" style="color: black">
                                        <i class="fa fa-user" ></i>&nbsp;{{ pass_request.status }}

                                    </span>

                            {% endif %}
                    <br>

                                <span role="presentation" class="tooltip-link" data-original-title="Bearable Cost"
                                    data-toggle="tooltip">
                                    <i class="fa fa-money"></i>&nbsp;
                                    ₦ {{ pass_request.bearable }} / ₦ {{ pass_request.ride.cost }}
                                </span>
                    <br>

                                <a class="" style="text-decoration: none" href="{{ pass_request.user.get_absolute_url }}" class="tooltip-link" data-original-title="User"
                                   data-toggle="tooltip">
                                    {% if pass_request.user.sex == 'Male' %}
                                        <i class="fa fa-male"></i> &nbsp;{{ pass_request.user.username }}
                                    {% elif pass_request.user.sex == 'Female' %}
                                        <i class="fa fa-female"></i> &nbsp;{{ pass_request.user.username }}
                                    {% else  %}
                                        <i class="fa fa-male"></i><i class="fa fa-female"></i>&nbsp;
                                    {% endif %}
                                </a>
                    <br>
                    <br>
                    <br>

                                {% if not pass_request.ride.ended and pass_request.status != 'canceled' %}
                                    {% if pass_request.status == 'approved' %}
                                        <a href="{% url 'app:request_driver_deny' pass_request.id %}" style="cursor: pointer;text-decoration: none" class="btn-danger btn-sm btn" >  <i class="fa fa-close "></i>&nbsp;Deny </a>
                                    {% elif pass_request.status == 'denied' %}
                                        <a href="{% url 'app:request_driver_approve' pass_request.id %}" style="cursor: pointer;text-decoration: none" class="btn-success btn-sm btn" >  <i class="fa fa-check "></i>&nbsp;Approve </a>
                                    {% else %}
                                        <a href="{% url 'app:request_driver_approve' pass_request.id %}" style="cursor: pointer;text-decoration: none" class=" btn-success btn-sm btn">  <i class="fa fa-check "></i>&nbsp;Approve </a>&nbsp;
                                        <a href="{% url 'app:request_driver_deny' pass_request.id %}" style="cursor: pointer;text-decoration: none" class="btn-danger btn-sm btn" >  <i class="fa fa-close "></i>&nbsp;Deny </a>
                                    {% endif %}
                                {% endif %}






                    </div>
                </div>
                {% endfor %}

                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>


    </div><!-- end .main-content -->

{% endblock %}

app/templates/app/request/single_request.html
{% extends 'app/user/main_template.html' %}
{% load staticfiles %}
{% load humanize %}

{% block cont-header %}
    <section class="content-header">
        <h1>
            Request <small> - from {{ user_requests.user }} {{ user_requests.reg_date|naturaltime }}</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i> Home</a></li>
            {% ifequal request.user.user_type 'Driver' %}
            <li><a href="{% url 'app:view_shared' request.user.id %}"><i class="fa fa-cab"></i> Shared Rides</a></li>
            {% endifequal %}
            <li class="active">{{ user_requests.ride }}</li>
        </ol>
    </section>
{% endblock %}
{% block body%}
    <div class="content-wrapper" style="min-height: 1126px;">
        <!-- Content Header (Page header) -->


        <!-- Main content -->
        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <!-- Widget: user widget style 1 -->
                    <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="widget-user-header bg-blue-gradient">
                            <div class="widget-user-image">
                                <img class="img-circle" src="{{ user_requests.user.get_profile.picture.url }}" alt="User Avatar">
                            </div>
                            <!-- /.widget-user-image -->
                            <h3 class="widget-user-username"><a class="text-bold text-black" href="{{ user_requests.user.get_absolute_url }}" >{{ user_requests.user|capfirst }}</a></h3>
                            <h6 class="widget-user-desc"><a class="alert-link" href="{{ user_requests.user.get_absolute_url }}">{{ user_requests.user.full_name|capfirst }}</a></h6>
                        </div>
                        <div class="box-footer no-padding">
                            <ul class="nav nav-stacked">
                                <li><a href="{{ user_requests.ride.get_absolute_url }}">&nbsp;{{ user_requests.ride }} <span class="pull-left badge bg-light-blue-gradient">&nbsp;Requested Ride&nbsp;<i class="fa fa-cab"></i></span></a></li>
                                <li><a >&nbsp;{{ user_requests.user.sex }} <span class="pull-left badge bg-light-blue-gradient">&nbsp;Sex&nbsp;<i class="fa fa-circle-o-notch"></i></span></a></li>
                                <li><a >&nbsp;{{ user_requests.user.no_of_request_completed|apnumber }} <span class="pull-left badge bg-light-blue-gradient">&nbsp;Rides Taken&nbsp;<i class="fa fa-car"></i></span></a></li>

                                <li><a >&nbsp;₦ {{ user_requests.bearable }}/   ₦ {{ user_requests.ride.cost }} <span class="pull-left badge bg-green">&nbsp;Bearable Cost&nbsp;<i class="fa fa-money"></i></span></a></li>

                                {% if user_requests.status == 'approved' %}
                                    <li class="ride-people">
                                        <a style="color: green">
                                            &nbsp;<i class="fa fa-user" ></i>&nbsp;{{ user_requests.status }}&nbsp;
                                            <span class="pull-left badge bg-green">&nbsp;Status&nbsp;<i class="fa fa-info"></i></span>
                                        </a>
                                    </li><!-- end .ride-people -->
                                {% elif user_requests.status == 'denied' %}
                                    <li class="ride-people">
                                        <a  style="color: red">
                                            &nbsp; <i class="fa fa-user" ></i>&nbsp;{{ user_requests.status }}&nbsp;
                                            <span class="pull-left badge bg-red">&nbsp;Status&nbsp;<i class="fa fa-info"></i></span>
                                        </a>
                                    </li><!-- end .ride-people -->
                                {% else %}
                                    <li class="ride-people">
                                        <a  style="color: black">
                                            &nbsp;<i class="fa fa-user" ></i>&nbsp;{{ user_requests.status }}&nbsp;
                                            <span class="pull-left badge bg-black">&nbsp;Status&nbsp;<i class="fa fa-info"></i></span>
                                        </a>
                                    </li><!-- end .ride-people -->
                                {% endif %}

                                <li><a href="{{ user_requests.ride.user.get_absolute_url }}">&nbsp;{{ user_requests.ride.user }} <span class="pull-left badge bg-light-blue-gradient">&nbsp;Driver&nbsp;<i class="fa fa-user-md"></i></span></a></li>
                            <li>
                                {% if user_requests.ride.user == request.user %}
                                {% if not user_requests.ride.ended and user_requests.status != 'canceled' %}
                                    {% if user_requests.status == 'approved' %}
                                        <a href="{% url 'app:request_driver_deny' user_requests.id %}" style="cursor: pointer;text-decoration: none" class="btn-danger btn-sm btn" >  <i class="fa fa-close "></i>&nbsp;Deny </a>
                                    {% elif pass_requests.status == 'denied' %}
                                        <a href="{% url 'app:request_driver_approve' user_requests.id %}" style="cursor: pointer;text-decoration: none" class="btn-success btn-sm btn" >  <i class="fa fa-check "></i>&nbsp;Approve </a>
                                    {% else %}
                                        <a href="{% url 'app:request_driver_approve' user_requests.id %}" style="cursor: pointer;text-decoration: none" class=" btn-success btn-sm btn">  <i class="fa fa-check "></i>&nbsp;Approve </a>&nbsp;
                                        <a href="{% url 'app:request_driver_deny' user_requests.id %}" style="cursor: pointer;text-decoration: none" class="btn-danger btn-sm btn" >  <i class="fa fa-close "></i>&nbsp;Deny </a>
                                    {% endif %}
                                {% endif %}
                                {% endif %}

                            </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.widget-user -->
                </div>
            </div>
        </section>
    </div>

{% endblock %}