Carpool/urls.py
from django.conf.urls import include, url,patterns
from django.contrib import admin
import app
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from os import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^broadcast/', include('broadcast.urls')),
    url(r'^$', app.views.IndexView.as_view()),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url('', include('app.urls')),


]

urlpatterns += patterns('',
        url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),)

# urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

api/urls.py
from django.conf.urls import include, url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [


    url(r'^users/$',views.UserList.as_view(), name='users'),

    url(r'^login/$',views.process_login, name='api_login'),

    url(r'^broadcasts/$',views.BroadcastList.as_view(), name='broadcasts'),
    url(r'^messages/$',views.MessageList.as_view(), name='messages'),
    url(r'^get_user/$',views.UserDetail.as_view(), name='user'),
    url(r'^getdashboard/$',views.DashStuff.as_view(), name='dashstuff'),
    url(r'^addride/$',views.addride, name='addride'),
    url(r'^userrides/$',views.UserVehicles.as_view(), name='userride'),
    url(r'^usershared/$',views.UserSharedVehicles.as_view(), name='usershared'),
    url(r'^requests/$',views.Requests.as_view(), name='requests'),



    # url(r'^upload/$',views.upload_file,name='upload'),
]

urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls'))
]

urlpatterns = format_suffix_patterns(urlpatterns)

app/urls.py
from django.conf.urls import url
from app import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/login/$', views.login_user, name='login_user'),

    url(r'^signup/$', views.CreateUser.as_view(), name='sign_up'),

    url(r'^user/(?P<pk>[0-9]+)/$', views.view_user_id, name='profile'),

    url(r'^profile/(?P<user_id>[a-zA_Z0-9]+)/$', views.view_user_name, name='user-profile'),
    url(r'^user/dashboard/$', views.dashboard, name='dashboard'),
    url(r'^user/dashboard/messages/$', views.messages, name='dashboard_messages'),
    url(r'^user/dashboard/notifications/$', views.notifications, name='dashboard_notifications'),

    url(r'^accounts/profile/$', views.create_profile, name='profile_make'),


    url(r'^user/dashboard/sent/$', views.sent, name='dashboard_sent'),

    url(r'^user/dashboard/junk/$', views.messages_junk, name='dashboard_junk'),
    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/read/$', views.messages_read, name='dashboard_messages_read'),
    url(r'^user/dashboard/sent/(?P<message_id>[0-9]+)/read/$', views.messages_read_sent, name='dashboard_messages_read_sent'),

    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/reply/$', views.messages_reply, name='dashboard_messages_reply'),

    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/forward/$', views.messages_forward, name='dashboard_messages_forward'),

    url(r'^user/dashboard/messages/compose/$', views.messages_compose, name='dashboard_messages_compose'),


    url(r'^accounts/login/$', views.login_user, name='login_user'),
    url(r'^terms/$', views.terms, name='terms'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^ride/(?P<user_id>[0-9]+)/$', views.ride, name='ride'),
    url(r'^ride/$', views.ride, name='ride'),

    url(r'^follow/(?P<followee>[0-9]+)/(?P<follower>[0-9]+)/$',views.do_follow,name='follow'),

    url(r'^user/(?P<pk>[0-9]+)/update-profile/$', views.EditUser.as_view(), name='user_update'),

    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^login/$', views.do_login, name='login'),



    url(r'^user/(?P<user_id>[0-9]+)/add-ride/$', views.vehicle_create, name='add_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/view-rides/$', views.vehicle_view, name='view_rides'),

    url(r'^user/(?P<user_id>[0-9]+)/delete-ride/(?P<vehicle_id>[0-9]+)/$', views.vehicle_delete, name='delete_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/share-ride/(?P<vehicle_id>[0-9]+)/$', views.vehicle_share, name='share_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/view-shared/$', views.vehicle_shared_view, name='view_shared'),

    url(r'^user/(?P<user_id>[0-9]+)/search/$', views.vehicle_search, name='search_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/request/(?P<ride_id>[0-9]+)', views.request_ride, name='request_ride'),

    url(r'^sharing/(?P<vehicle_share_id>[0-9]+)/view/$', views.view_single_ride, name='view_shared_ride'),

    url(r'^ride/(?P<ride_id>[0-9]+)/view/$', views.view_single_vehicle, name='view_shared_vehicle'),

    url(r'^sharing/(?P<user_id>[0-9]+)/delete/(?P<vehicle_share_id>[0-9]+)/$', views.vehicle_share_delete, name='delete_shared_ride'),

    url(r'^requests/(?P<user_id>[0-9]+)/view$', views.requests_driver_view, name='request_driver_view'),
    url(r'^requests/all$',views.all_ride_requests, name='view_ride_requests'),
    url(r'^request/(?P<request_id>[0-9]+)/approve/$', views.request_approve, name='request_driver_approve'),
    url(r'^request/(?P<request_id>[0-9]+)/deny/$', views.request_deny, name='request_driver_deny'),

    # url(r'^requests/(?P<user_id>[0-9]+)/view$', views.requests_driver_view, name='request_driver_view'),

    url(r'^request/(?P<request_id>[0-9]+)/view/$', views.request_view, name='request_view'),

    url(r'^user/(?P<user_id>[0-9]+)/requests/$', views.requests_user_view, name='requests_user_view'),

    url(r'^request/(?P<request_id>[0-9]+)/delete/$', views.request_delete, name='request_delete'),

    url(r'^notification/read/$', views.mark_as_read, name='mark_as_read'),

    url(r'^user/messages/unread/$', views.unread_messages, name='unread_messages'),
    url(r'^user/messages/(?P<message_id>[0-9]+)/delete/$', views.delete_message, name='delete_message'),

    url(r'^user/preferences/$', views.preferences, name='preferences'),

     url(r'^user/preferences/image-update$', views.image_update, name='image_update'),

    url(r'^user/preferences/basic-update$', views.basic_update, name='basic_update'),
    url(r'^user/preferences/user-update$', views.user_update, name='user_update'),
    url(r'^user/preferences/driver-update$', views.driver_update, name='driver_update'),
    url(r'^user/preferences/bio-update$', views.bio_update, name='bio_update'),
    url(r'^user/preferences/app-update$', views.app_update, name='app_update'),
    url(r'^user/preferences/social-update$', views.social_update, name='social_update'),
    url(r'^user/preferences/password-update$', views.password_update, name='password_update'),




]

app/templates/app/dashboard/dashboard_home.html
{% extends 'app/dashboard/dashboard_template.html' %}

{% block heading %}
    <section class="content-header">
        <h1>
            Dashboard
            <small>Overview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i>Dashboard</a></li>
            <li class="active">&nbsp;Overview</li>
        </ol>
    </section>
{% endblock %}

{% block content %}

    <section class="content">
        {% if request.user.user_type == 'Driver' %}
            <div class="row">
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-aqua">
                        <div class="inner">
                            <h3>{{ vehicle.count }}</h3>

                            <p>Vehicles</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-car"></i>
                        </div>
                        <a href="{% url 'app:view_rides' request.user.id %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-green">
                        <div class="inner">
                            <h3>{{ vehicle_share.count }}</h3>

                            <p>Shared Rides</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-users"></i>
                        </div>
                        <a href="{% url 'app:view_shared' request.user.id %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-yellow">
                        <div class="inner">
                            <h3>{{ request_in.count }}</h3>

                            <p>Ride Requests</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-list"></i>
                        </div>
                        <a href="{% url 'app:view_ride_requests' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-red">
                        <div class="inner">
                            <h3>{{ request.user.get_no_followers }}</h3>
                            <p>Followers</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-globe"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>

            <div class="row">
                <div class="col-xs-12">
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        {% else %}
            <div class="row">
                <!-- ./col -->
                <!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-yellow">
                        <div class="inner">
                            <h3>{{ request_out.count }}</h3>

                            <p>Requested Rides</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-reorder"></i>
                        </div>
                        <a href="{% url 'app:requests_user_view' request.user.id %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-red">
                        <div class="inner">
                            <h3>{{ request.user.get_no_followers }}</h3>

                            <p>Followers</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-globe"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>
        {% endif %}

    </section>

{% endblock %}

app/templates/app/dashboard/dashboard_messages.html
{% extends 'app/dashboard/dashboard_template.html' %}
{% load humanize %}
{% block heading %}
    <section class="content-header">
        <h1>
            Dashboard
            <small>Messages</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i>Dashboard</a></li>
            <li class="active">&nbsp;Messages</li>
        </ol>
    </section>
{% endblock %}


{% block content %}

    <section class="content">

        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'app:dashboard_messages_compose' %}" class="btn btn-primary btn-block margin-bottom">Compose</a>

                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">Folders</h3>

                        <div class="box-tools">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                    class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li class="active"><a href="#"><i class="fa fa-inbox"></i> Inbox
                                <span class="label label-primary pull-right">{{ request.user.get_no_messages|default_if_none:'0 new' }}</span></a></li>
                            <li><a href="{% url 'app:dashboard_sent' %}"><i class="fa fa-envelope-o"></i> Sent</a></li>
                            <li><a href="{% url 'app:dashboard_junk' %}"><i class="fa fa-trash-o"></i> Trash</a></li>
                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /. box -->

            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Inbox</h3>


                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body no-padding">

                            <table class="table table-responsive table-hover table-striped" id="mail_table">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th aria-sort="descending">Date</th>
                                    <th>Sender</th>
                                    <th>Message</th>
                                    <th>Read</th>

                                </tr>
                                </thead>

                                <tbody>
                                {% for message in messages %}
                                    <tr>
                                        <td class="mailbox-star"><a href=""><i class="text-green fa fa-folder-open{% if not message.read %} text-orange   {% endif %} "></i></a></td>

                                        <td class="mailbox-date">{{ message.date|date }}</td>

                                        <td class="mailbox-name"><a href="{% url 'app:dashboard_messages_read' message.id %}" class="text-bold">{{ message.sender.full_name }}</a></td>
                                        <td class="mailbox-subject"><b>{{ message.subject }}</b> -  {{ message.message|striptags|truncatechars:20 }}...
                                        </td>

                                        <td><a href="{% url 'app:delete_message' message.id %}" role="button" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i>
                                        </a></td>
                                    </tr>
                                {% endfor %}


                                </tbody>
                            </table>
                            <!-- /.table -->

                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer no-padding">

                    </div>
                </div>
                <!-- /. box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->


    </section>

{% endblock %}

app/templates/app/dashboard/dashboard_messages_compose.html
{% extends 'app/dashboard/dashboard_template.html' %}
{% load humanize %}
{% load staticfiles %}
{% block heading %}
    <section class="content-header">
        <h1>
            Dashboard
            <small>Messages</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i>Dashboard</a></li>
            <li><a href="{% url 'app:dashboard_messages' %}"><i class="fa fa-dashboard"></i>Messages</a></li>
            <li class="active">&nbsp;Read Message</li>

        </ol>
    </section>
{% endblock %}


{% block content %}

    <section class="content">

        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'app:dashboard_messages_compose' %}" class="btn btn-primary btn-block margin-bottom">Compose</a>

                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">Folders</h3>

                        <div class="box-tools">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                    class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="{% url 'app:dashboard_messages' %}"><i class="fa fa-inbox"></i>
                                Inbox
                                <span class="label label-primary pull-right">{{ request.user.get_no_messages|default_if_none:'0 new' }}</span></a>
                            </li>
                            <li><a href="{% url 'app:dashboard_sent' %}"><i class="fa fa-envelope-o"></i> Sent</a></li>
                            <li><a href="{% url 'app:dashboard_junk' %}"><i class="fa fa-trash-o"></i> Trash</a></li>
                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /. box -->

            </div>
            <!-- /.col -->

            <div class="col-md-9">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Compose New Message</h3>
                    </div>
                    <!-- /.box-header -->
                    <form action="" method="post" validate>
                        {% csrf_token %}
                        <div class="box-body">

                            <div class="form-group">
                                <input class="form-control " placeholder="To: (recipients username) " name="to" {% if recipient %}
                                    value="{{ recipient }}" readonly
                                {% endif %} required onblur="validate(this)">
                                <span class="label label-danger" id="error"></span>

                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Subject:" name="subject" {% if subject %}
                                value="{{ subject }}" readonly
                                {% endif %} required>
                            </div>
                            <div class="form-group">
                    <textarea id="compose-textarea" class="form-control" style="height: 300px" name="message" required>{% if message %}{{ message }}{% endif %}</textarea >
                            </div>

                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <div class="pull-right">

                                <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Send
                                </button>
                            </div>
                            <button type="reset" class="btn btn-default"><i class="fa fa-times"></i> Discard</button>
                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>
                <!-- /. box -->
                <!-- /. box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->


    </section>

    <script src="{% static 'app/customnotify/mailsend.js' %}"></script>
{% endblock %}

app/templates/app/dashboard/dashboard_messages_junk.html
{% extends 'app/dashboard/dashboard_template.html' %}
{% load humanize %}
{% block heading %}
    <section class="content-header">
        <h1>
            Dashboard
            <small>Messages</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i>Dashboard</a></li>
            <li class="active">&nbsp;Messages</li>
        </ol>
    </section>
{% endblock %}


{% block content %}

    <section class="content">

        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'app:dashboard_messages_compose' %}" class="btn btn-primary btn-block margin-bottom">Compose</a>

                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">Folders</h3>

                        <div class="box-tools">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                    class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li ><a href="{% url 'app:dashboard_messages' %}"><i class="fa fa-inbox"></i> Inbox
                                <span class="label label-primary pull-right">{{ request.user.get_no_messages|default_if_none:'0 new' }}</span></a></li>
                            <li><a href="{% url 'app:dashboard_sent' %}"><i class="fa fa-envelope-o"></i> Sent</a></li>
                            <li class="active"><a href="{% url 'app:dashboard_junk' %}"><i class="fa fa-trash-o"></i> Trash</a></li>
                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /. box -->

            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Trash</h3>


                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body no-padding">

                        <table class="table table-responsive table-hover table-striped" id="mail_table">
                            <thead>
                            <tr>
                                <th>Read</th>
                                <th aria-sort="descending">Date</th>
                                <th>Sender</th>
                                <th>Message</th>


                            </tr>
                            </thead>

                            <tbody>
                            {% for message in messages %}
                                <tr>
                                    <td class="mailbox-star"><a href=""><i class="fa fa-folder-open{% if not message.read %}-o{% endif %} text-info"></i></a></td>

                                    <td class="mailbox-date">{{ message.date|date }}</td>

                                <td class="mailbox-name"><a href="{% url 'app:dashboard_messages_read' message.id %}" class="text-bold">{{ message.sender.full_name }}</a></td>
                                <td class="mailbox-subject"><b>{{ message.subject }}</b> -  {{ message.message|striptags|truncatechars:20 }}
                                </td>

</tr>
                            {% endfor %}


                            </tbody>
                        </table>
                        <!-- /.table -->

                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer no-padding">

                    </div>
                </div>
                <!-- /. box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->


    </section>

{% endblock %}

app/templates/app/dashboard/dashboard_messages_read.html
{% extends 'app/dashboard/dashboard_template.html' %}
{% load humanize %}
{% block heading %}
    <section class="content-header">
        <h1>
            Dashboard
            <small>Messages</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i>Dashboard</a></li>
            <li><a href="{% url 'app:dashboard_messages' %}"><i class="fa fa-dashboard"></i>Messages</a></li>
            <li class="active">&nbsp;Read Message</li>

        </ol>
    </section>
{% endblock %}


{% block content %}

    <section class="content">

        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'app:dashboard_messages_compose' %}" class="btn btn-primary btn-block margin-bottom">Compose</a>

                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">Folders</h3>

                        <div class="box-tools">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                    class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li class="active"><a href="{% url 'app:dashboard_messages' %}"><i class="fa fa-inbox"></i> Inbox
                                <span class="label label-primary pull-right">{{ request.user.get_no_messages|default_if_none:'0 new' }}</span></a></li>
                            <li><a href="{% url 'app:dashboard_sent' %}"><i class="fa fa-envelope-o"></i> Sent</a></li>
                            <li><a href="{% url 'app:dashboard_junk' %}"><i class="fa fa-trash-o"></i> Trash</a></li>
                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /. box -->

            </div>
            <!-- /.col -->

            <div class="col-md-9">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Read Messages</h3>

                        <div class="box-tools pull-right">
                            <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="" data-original-title="Previous"><i class="fa fa-chevron-left"></i></a>
                            <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="" data-original-title="Next"><i class="fa fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body no-padding">
                        <div class="mailbox-read-info">
                            <h3>{{ message.subject }}</h3>
                            {% if recipient %}
                            <h5> From:<a href="{{ message.sender.get_absolute_url }}"> {{ message.sender.full_name }}</a>
                                <span class="mailbox-read-time pull-right">{{ message.date }}</span></h5>
                            {% else  %}
                                <h5> To:<a href="{{ message.recipient.get_absolute_url }}"> {{ message.recipient.full_name }}</a>
                                    <span class="mailbox-read-time pull-right">{{ message.date }}</span></h5>
                            {% endif %}
                        </div>
                        <!-- /.mailbox-read-info -->

                        <!-- /.mailbox-controls -->
                        <div class="mailbox-read-message " id="read-message">

                                <p>{{ message.message|safe }}</p>

                        </div>
                        <!-- /.mailbox-read-message -->
                    </div>
                    <!-- /.box-body -->

                    <!-- /.box-footer -->
                    <div class="box-footer">
                        <div class="pull-right">
                            {% if recipient %}
                            <a href="{% url 'app:dashboard_messages_reply' message.id %}" role="button" class="btn btn-default"><i class="fa fa-reply"></i> Reply</a>
                            {%endif%}
                            <a href="{% url 'app:dashboard_messages_forward' message.id %}" role="button" class="btn btn-default"><i class="fa fa-share"></i> Forward</a>
                        </div>
                        {% if recipient %}
                        <a href="{% url 'app:delete_message' message.id %}" role="button" class="btn btn-default"><i class="fa fa-trash-o"></i> Delete</a>
                        {% endif %}
                        <button role="button" class="btn btn-default" onclick="window.print()"><i class="fa fa-print"></i> Print</button>

                    </div>
                    <!-- /.box-footer -->
                </div>
                <!-- /. box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->


    </section>

{% endblock %}

app/templates/app/dashboard/notice.html
<div class="alert alert-block alert-{{ notice.level }}">
  <a class="close pull-right" href="{% url 'notifications:mark_as_read' notice.slug %}">
    <i class="icon-close"></i>
  </a>
  
  <h4>
    <i class="icon-mail{% if notice.unread %}-alt{% endif %}"></i>
    {{ notice.actor }} 
    {{ notice.verb }}
    {% if notice.target %}
      of {{ notice.target }}
    {% endif %}
  </h4>
  
  <p>{{ notice.timesince }} ago</p>
  
  <p>{{ notice.description|linebreaksbr }}</p>
  
  <div class="notice-actions">
    {% for action in notice.data.actions %}
      <a class="btn" href="{{ action.href }}">{{ action.title }}</a>
    {% endfor %}
  </div>
</div>