Carpool/urls.py
from django.conf.urls import include, url,patterns
from django.contrib import admin
import app
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from os import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^broadcast/', include('broadcast.urls')),
    url(r'^$', app.views.IndexView.as_view()),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url('', include('app.urls')),


]

urlpatterns += patterns('',
        url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),)

# urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

api/urls.py
from django.conf.urls import include, url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [


    url(r'^users/$',views.UserList.as_view(), name='users'),

    url(r'^login/$',views.process_login, name='api_login'),

    url(r'^broadcasts/$',views.BroadcastList.as_view(), name='broadcasts'),
    url(r'^messages/$',views.MessageList.as_view(), name='messages'),
    url(r'^get_user/$',views.UserDetail.as_view(), name='user'),
    url(r'^getdashboard/$',views.DashStuff.as_view(), name='dashstuff'),
    url(r'^addride/$',views.addride, name='addride'),
    url(r'^userrides/$',views.UserVehicles.as_view(), name='userride'),
    url(r'^usershared/$',views.UserSharedVehicles.as_view(), name='usershared'),
    url(r'^requests/$',views.Requests.as_view(), name='requests'),



    # url(r'^upload/$',views.upload_file,name='upload'),
]

urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls'))
]

urlpatterns = format_suffix_patterns(urlpatterns)

app/urls.py
from django.conf.urls import url
from app import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/login/$', views.login_user, name='login_user'),

    url(r'^signup/$', views.CreateUser.as_view(), name='sign_up'),

    url(r'^user/(?P<pk>[0-9]+)/$', views.view_user_id, name='profile'),

    url(r'^profile/(?P<user_id>[a-zA_Z0-9]+)/$', views.view_user_name, name='user-profile'),
    url(r'^user/dashboard/$', views.dashboard, name='dashboard'),
    url(r'^user/dashboard/messages/$', views.messages, name='dashboard_messages'),
    url(r'^user/dashboard/notifications/$', views.notifications, name='dashboard_notifications'),

    url(r'^accounts/profile/$', views.create_profile, name='profile_make'),


    url(r'^user/dashboard/sent/$', views.sent, name='dashboard_sent'),

    url(r'^user/dashboard/junk/$', views.messages_junk, name='dashboard_junk'),
    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/read/$', views.messages_read, name='dashboard_messages_read'),
    url(r'^user/dashboard/sent/(?P<message_id>[0-9]+)/read/$', views.messages_read_sent, name='dashboard_messages_read_sent'),

    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/reply/$', views.messages_reply, name='dashboard_messages_reply'),

    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/forward/$', views.messages_forward, name='dashboard_messages_forward'),

    url(r'^user/dashboard/messages/compose/$', views.messages_compose, name='dashboard_messages_compose'),


    url(r'^accounts/login/$', views.login_user, name='login_user'),
    url(r'^terms/$', views.terms, name='terms'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^ride/(?P<user_id>[0-9]+)/$', views.ride, name='ride'),
    url(r'^ride/$', views.ride, name='ride'),

    url(r'^follow/(?P<followee>[0-9]+)/(?P<follower>[0-9]+)/$',views.do_follow,name='follow'),

    url(r'^user/(?P<pk>[0-9]+)/update-profile/$', views.EditUser.as_view(), name='user_update'),

    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^login/$', views.do_login, name='login'),



    url(r'^user/(?P<user_id>[0-9]+)/add-ride/$', views.vehicle_create, name='add_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/view-rides/$', views.vehicle_view, name='view_rides'),

    url(r'^user/(?P<user_id>[0-9]+)/delete-ride/(?P<vehicle_id>[0-9]+)/$', views.vehicle_delete, name='delete_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/share-ride/(?P<vehicle_id>[0-9]+)/$', views.vehicle_share, name='share_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/view-shared/$', views.vehicle_shared_view, name='view_shared'),

    url(r'^user/(?P<user_id>[0-9]+)/search/$', views.vehicle_search, name='search_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/request/(?P<ride_id>[0-9]+)', views.request_ride, name='request_ride'),

    url(r'^sharing/(?P<vehicle_share_id>[0-9]+)/view/$', views.view_single_ride, name='view_shared_ride'),

    url(r'^ride/(?P<ride_id>[0-9]+)/view/$', views.view_single_vehicle, name='view_shared_vehicle'),

    url(r'^sharing/(?P<user_id>[0-9]+)/delete/(?P<vehicle_share_id>[0-9]+)/$', views.vehicle_share_delete, name='delete_shared_ride'),

    url(r'^requests/(?P<user_id>[0-9]+)/view$', views.requests_driver_view, name='request_driver_view'),
    url(r'^requests/all$',views.all_ride_requests, name='view_ride_requests'),
    url(r'^request/(?P<request_id>[0-9]+)/approve/$', views.request_approve, name='request_driver_approve'),
    url(r'^request/(?P<request_id>[0-9]+)/deny/$', views.request_deny, name='request_driver_deny'),

    # url(r'^requests/(?P<user_id>[0-9]+)/view$', views.requests_driver_view, name='request_driver_view'),

    url(r'^request/(?P<request_id>[0-9]+)/view/$', views.request_view, name='request_view'),

    url(r'^user/(?P<user_id>[0-9]+)/requests/$', views.requests_user_view, name='requests_user_view'),

    url(r'^request/(?P<request_id>[0-9]+)/delete/$', views.request_delete, name='request_delete'),

    url(r'^notification/read/$', views.mark_as_read, name='mark_as_read'),

    url(r'^user/messages/unread/$', views.unread_messages, name='unread_messages'),
    url(r'^user/messages/(?P<message_id>[0-9]+)/delete/$', views.delete_message, name='delete_message'),

    url(r'^user/preferences/$', views.preferences, name='preferences'),

     url(r'^user/preferences/image-update$', views.image_update, name='image_update'),

    url(r'^user/preferences/basic-update$', views.basic_update, name='basic_update'),
    url(r'^user/preferences/user-update$', views.user_update, name='user_update'),
    url(r'^user/preferences/driver-update$', views.driver_update, name='driver_update'),
    url(r'^user/preferences/bio-update$', views.bio_update, name='bio_update'),
    url(r'^user/preferences/app-update$', views.app_update, name='app_update'),
    url(r'^user/preferences/social-update$', views.social_update, name='social_update'),
    url(r'^user/preferences/password-update$', views.password_update, name='password_update'),




]

app/templates/app/vehicles/share_ride.html
{% extends 'app/user/main_template.html' %}
{% load  static %}
{% load humanize %}



{% block cont-header %}
    <section class="content-header">
        <h1>
            Share Ride <small> - Complete the form to share a ride</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i> Home</a></li>
            <li><a href="{% url 'app:view_rides' request.user.id %}"><i class="fa fa-cab"></i> View/Share rides</a></li>
            <li class="active">Share ride</li>
        </ol>
    </section>
{% endblock %}


{% block body %}

    <div class="register-box hold-transition register-page box box-info">
        <div class="register-box-body">
            <h3 class="login-box-msg "><i class="fa fa-cab"></i>&nbsp;Vehicle Sharing</h3>

            <form  action="" validate autocomplete="off" class="" role="form" method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {% include 'app/template_form.html' %}

                <div class="field buttons ">
                    <button type="submit" class="btn btn-lg bg-blue form-control-static">Share</button>
                </div>

                <span id="invalid"></span>

            </form>

        </div>
        <!-- /.form-box -->
    </div>

    <!-- /.register-box -->




{% endblock %}

app/templates/app/vehicles/vehicle_search.html
{% extends 'app/user/main_template.html' %}
{% load staticfiles %}
{% load humanize %}


{% block cont-header %}
    <section class="content-header">
        <h1>
            Search Ride <small>- Find a ride to join from available destinations</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Search Ride</li>
        </ol>
    </section>
{% endblock %}

{% block body %}

    <section class="content">
    <div class="page-header">Filter by any of the following<small class="page-sub-title">leave blank to view all available rides</small></div>


        <!-- =========================================================== -->
        <form action="{% url 'app:search_ride' request.user.id %}" method="post" novalidate autocomplete="on" >
            {% csrf_token %}
        <div class="row">
            <div class="col-md-3">
                <div class="box box-info " style="height: 98px;">
                    <div class="box-header with-border">
                        <h3 class="box-title">All Places</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool"><i class="fa fa-map-marker"></i>
                            </button>
                        </div>
                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <select class="form-control select2 " name="source" style="width: 100%; border-radius: 0px">
                            <option class="default"></option>
                            {% for ride in allrides %}
                            <option>{{ ride.start }}</option>
                                <option>{{ ride.dest }}</option>
                            {% endfor %}


                        </select>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
            <div class="col-md-3">
                <div class="box box-info " style="height: 98px;">
                    <div class="box-header with-border">
                        <h3 class="box-title">Date</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" ><i class="fa fa-calendar"></i>
                            </button>
                        </div>
                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="input-group date" style="width: 100%; border-radius: 0px">

                           <input type="text" class="datepicker form-control" id="datepicker" name="date" data-date-start-date="0d" />

                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
            <div class="col-md-3">
                <div class="box box-info " style="height: 98px;">
                    <div class="box-header with-border">
                        <h3 class="box-title">Vehicle Type</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" ><i class="fa fa-car"></i>
                            </button>
                        </div>
                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <select class="select2 form-control" style="width: 100%; border-radius: 0px" name="vehicle_type">
                            <option class="default" ></option>
                        <option>Car</option>
                        <option>Bus</option>
                        <option>Coaster</option>
                        <option>Truck</option>
                        </select>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>

            <!-- /.col -->
            <div class="col-md-3">

            <br>

            <!-- /.box-header -->
            <div class="">
                <button type="submit" class="btn btn-flat btn-block btn-primary btn-md" style="float:bottom;" onsubmit="this.innerHTML='Searching...'">Search</button>
            </div>
            <!-- /.box-body -->

    <!-- /.col -->
        </div>
</div>
</form>
    </section>

    <div class="content-wrapper" style="min-height: 1126px;">
    {% ifnotequal size 0 %}
        <div class="page-header"><small class="page-sub-title">Search results ({{ size}})</small></div>
        {% else %}
        <div class="page-header"><small class="page-sub-title">No Results</small>try another search or</div>
        <a href="{% url 'app:index' %}#ride-broadcast" class="btn btn-primary btn-lg"><i class="fa fa-bullhorn"></i>&nbsp;Broadcast a Ride Request</a>
 {% endifnotequal %}

        {% for ride in rides %}
        <ul class="timeline">

            <!-- timeline time label -->
            <li class="time-label">
        <span class="bg-black">
            {{ ride.date|naturalday|capfirst }}
        </span>

            </li>
            <!-- /.timeline-label -->

            <!-- timeline item -->
            <li>

                <div class="timeline-item">
                    <span class="time"><i class="fa fa-clock-o"></i> {{ ride.start_time }}</span>

                    <h3 class="timeline-header">{{ ride }}&nbsp;-&nbsp;
                        <span><a href="{{ ride.vehicle.user.get_absolute_url }}">{{ ride.vehicle.user.username }}</a> </span>   </h3>

                    <div class="timeline-body">
                        <dl class="">
                            <dt>Ride Details: </dt>
                            <dd class=""><textarea style="width: 100%;height: 100%" class="form-control-static form-inline" readonly aria-readonly="true">{{ ride.details }}</textarea></dd>
                            {% if ride.pickuppoint %}
                            <dt>Pickup Point: </dt>
                            <dd>{{ ride.pickuppoint }}</dd>
                            {%endif%}
                            <dt>Gender Preference: </dt>
                            <dd>{{ ride.sex }}</dd>
                            <dt>Vehicle Type: </dt>
                            <dd>{{ ride.vehicle.type }}&nbsp;{{ ride.vehicle.category  }}</dd>
                            <dt>Number of Seats: </dt>
                            <dd>{{ ride.no_pass }}</dd>
                        </dl>
                    </div>

                    <div class="timeline-footer">
                        <a data-toggle="modal" class="btn btn-primary btn-xs" data-target="#add{{ ride.id }}" style="cursor: pointer;">
                            <i class="fa fa-plus"></i>
                            Join Ride
                        </a>
                        <a class="btn btn-success btn-xs pull-right">₦ {{ ride.cost }}</a>
                    </div>
                </div>
            </li>
            <!-- END timeline item -->
        </ul>

            <div class="modal modal-info" id="add{{ ride.id }}">
                <div class="modal-dialog ">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span></button>
                            <h4 class="modal-title">Ride : {{ ride|capfirst }}</h4>
                        </div>
                        <form action="{% url 'app:request_ride' user.id ride.id %}" validate autocomplete="off" class="idealforms" method="post" >
                            {% csrf_token %}
                            <div class="modal-body ">

                                <div class="log-header">
                                    <span class="log-in">Request to join Ride</span>
                                    <span class="">{{ ride }}</span>
                                </div>
                                <br>

                                <div class="field">
                                    <input name="pick" class="form-control" type="text" placeholder="Pick up point" required>
                                </div>
                                <br>

                                <div class="field">
                                    <input type="text" class="form-control" name="dest" placeholder="Destination" required>
                                </div>
                                <br>

                                <div class="field">
                                    <input type="number" class="form-control" name="bearable" placeholder="Bearable cost (In Naira (₦))" required>
                                </div>
                                <br>


                                <div class="clearfix"></div>



                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-outline pull-left" onloadstart="this.innerHTML='Searching...'">Join</button>

                        </div>
                        </form><!-- end .login -->
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>


        {% endfor %}
    </div>


{% endblock %}

app/templates/app/vehicles/view_shared.html
{% extends 'app/user/main_template.html' %}
{% load  static %}
{% load humanize %}


{% block cont-header %}
    <section class="content-header">
        <h1>
            View Shared <small> - You can manage your shared rides from here </small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">View Shared</li>
        </ol>
    </section>
{% endblock %}

{% block body %}


    <div class="content-wrapper" style="min-height: 1126px;">
        <!-- Content Header (Page header) -->




        {% if message %}
            <div class="callout callout-success">
                <h4>{{ message_heading}}</h4>

                <p>{{ message_body }}</p>
            </div>
        {% endif %}
        <!-- Main content -->
        <section class="content">
            <div class="row">
                {% if shared %}
                    {% for share in shared %}
                        <div class="col-sm-4 col-lg-3 col-md-3 col-space">
                            <div class="thumbnail">
                                <a >
                                    <img src="{% static 'app/img/ride.jpg' %}" class="img-responsive">
                                </a>

                                <div class="caption">
                                    <h3><a href="{% url 'app:view_shared_ride' share.id%}" >{{ share.start }} to {{ share.dest }}</a></h3>
                                    <h4><a href="{{ share.vehicle.get_absolute_url }}">Ride : {{ share.vehicle }}</a></h4>

                                    <p>Seating : {{ share.no_pass }} seats</p>

                                    <form action="{% url 'app:request_driver_view' user.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="share_id" value="{{ share.id }}"/>
                                        <button type="submit" class="btn btn-primary btn-sm panel-button">
                                            View Requests
                                        </button>
                                    </form>

                                    {% if not share.ended%}
                                    <form action="{% url 'app:delete_shared_ride' request.user.id share.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}

                                        <button type="submit" class="btn btn-danger btn-sm panel-button">
                                            <span class="glyphicon glyphicon-stop"></span>
                                        </button>
                                    </form>
                                    {% endif %}


{#                                    <a href="" class="btn btn-success btn-sm" role="button" >#}
{#                                        <span class="glyphicon glyphicon-pencil"></span>#}
{#                                    </a>#}



                                </div>
                            </div>

                        </div>
                        {% cycle '' ''  '' '<div class="clearfix hidden-xs hidden-sm"></div>' %}
                        {% cycle '' '' '<div class="clearfix visible-sm"></div>' %}

                    {% endfor %}

                {% else %}
                    <div class="col-sm-12">
                        <br>
                        <a href="{% url 'app:view_rides' request.user.id %}">
                            <button type="button" class="btn btn-success">
                                <span class="fa fa-group"></span>&nbsp; Share a Ride
                            </button>
                        </a>
                    </div>
                {% endif %}
            </div>
        </section>

    </div>

{% endblock %}

app/templates/app/vehicles/view_vehicles.html
{% extends 'app/user/main_template.html' %}
{% load  static %}
{% load humanize %}


{% block cont-header %}
    <section class="content-header">
        <h1>
            All Rides <small> - You can view, share and delete rides from here </small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">View Rides</li>
        </ol>
    </section>
{% endblock %}


{% block body %}
    <style>
        .user-row {
            margin-bottom: 14px;
        }

        .user-row:last-child {
            margin-bottom: 0;
        }

        .dropdown-user {
            margin: 13px 0;
            padding: 5px;
            height: 100%;
        }

        .dropdown-user:hover {
            cursor: pointer;
        }

        .table-user-information > tbody > tr {
            border-top: 1px solid rgb(221, 221, 221);
        }

        .table-user-information > tbody > tr:first-child {
            border-top: 0;
        }

        .table-user-information > tbody > tr > td {
            border-top: 0;
        }

        .toppad {
            margin-top: 20px;
        }

    </style>

    <div class="content-wrapper" style="min-height: 1126px;">
        {% if message %}
            <div class="callout callout-success">
                <h4>{{ message_title }}</h4>

                <p>{{ message_body }}</p>
            </div>
        {% endif %}
        <section class="content">
                {% if rides %}
                    {% for ride in rides %}
                        <div class="col-sm-4 col-lg-3 col-md-3 col-space">
                        <div class="thumbnail">
                            <a data-toggle="modal"
                               data-target="#loginModal{{ ride.id }}">
                                <img src="{% static 'app/img/chrysler_6.jpg' %}" class="img-responsive">
                            </a>

                            <div class="caption">
                                <h3>{{ ride.make }} {{ ride.model }}</h3>
                                <h4>Vechicle category: {{ ride.category }}</h4>

                                <p>Seating : {{ ride.seats }} seats</p>

                                <form action="{% url 'app:share_ride' user.id ride.id %}" method="get" style="display: inline;">
{#                                    {% csrf_token %}#}
{#                                    <input type="hidden" name="vehicle_id" value="{{ ride.id }}"/>#}
                                    <button type="submit" class="btn btn-primary btn-sm panel-button">
                                        Share ride
                                    </button>
                                </form>




                                <form action="{% url 'app:delete_ride' user.id ride.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="vehicle_id" value="{{ ride.id }}"/>
                                    <button type="submit" class="btn btn-danger btn-sm panel-button">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                                <a href="" class="btn btn-success btn-sm" role="button" data-toggle="modal"
                                   data-target="#loginModal{{ ride.id }}">
                                    <span class="glyphicon glyphicon-eye-open"></span>
                                </a>

                                <div class="modal fade" id="loginModal{{ ride.id }}" tabindex="-1" role="dialog"
                                     aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">

                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-hidden="true">&times;</button>
                                            </div><!-- end .modal-header -->
                                            <div class="modal-title">
                                                <p class="log-in text-bold text-center">Vehicle Details</p>
                                            </div>

                                            <div class="modal-body">
                                                <div class="row">

                                                    <div class=" col-md-12 col-lg-12 " align="center">
                                                        <table class="table table-user-information">
                                                            <tbody>
                                                            <tr class="user-row alert alert-info">
                                                                <td>VEHICLE NAME</td>
                                                                <td>{{ ride.make }} {{ ride.model }}</td>
                                                            </tr>
                                                            <tr class="user-row alert alert-info">
                                                                <td>YEAR OF PURCHASE</td>
                                                                <td>{{ ride.year }}</td>
                                                            </tr>
                                                            <tr class="user-row alert alert-info">
                                                                <td>CATEGORY</td>
                                                                <td>{{ ride.category }}</td>
                                                            </tr>
                                                            <tr class="user-row alert alert-info">
                                                                <td>SEATING</td>
                                                                <td>{{ ride.seats }}</td>
                                                            </tr>
                                                            <tr class="user-row alert alert-info">
                                                                <td>TYPE</td>
                                                                <td>{{ ride.type|capfirst }} Vehicle</td>
                                                            </tr>

                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div><!-- end .modal-body -->

                                        </div><!-- end .modal-content -->
                                    </div><!-- end .modal-dialog -->
                                </div><!-- end .modal -->


                            </div>
                        </div>

                        </div>
                        {% cycle '' ''  '' '<div class="clearfix hidden-xs hidden-sm"></div>' %}
                        {% cycle '' '' '<div class="clearfix visible-sm"></div>' %}

                    {% endfor %}

                {% else %}
                    <div class="col-sm-12">
                        <br>
                        <a href="{% url 'app:add_ride' request.user.id %} ">
                            <button type="button" class="btn btn-success">
                                <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a ride
                            </button>
                        </a>
                    </div>
                {% endif %}
                </section>
            </div>

    </div>
{% endblock %}