Carpool/urls.py
from django.conf.urls import include, url,patterns
from django.contrib import admin
import app
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from os import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^broadcast/', include('broadcast.urls')),
    url(r'^$', app.views.IndexView.as_view()),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url('', include('app.urls')),


]

urlpatterns += patterns('',
        url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),)

# urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

api/urls.py
from django.conf.urls import include, url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [


    url(r'^users/$',views.UserList.as_view(), name='users'),

    url(r'^login/$',views.process_login, name='api_login'),

    url(r'^broadcasts/$',views.BroadcastList.as_view(), name='broadcasts'),
    url(r'^messages/$',views.MessageList.as_view(), name='messages'),
    url(r'^get_user/$',views.UserDetail.as_view(), name='user'),
    url(r'^getdashboard/$',views.DashStuff.as_view(), name='dashstuff'),
    url(r'^addride/$',views.addride, name='addride'),
    url(r'^userrides/$',views.UserVehicles.as_view(), name='userride'),
    url(r'^usershared/$',views.UserSharedVehicles.as_view(), name='usershared'),
    url(r'^requests/$',views.Requests.as_view(), name='requests'),



    # url(r'^upload/$',views.upload_file,name='upload'),
]

urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls'))
]

urlpatterns = format_suffix_patterns(urlpatterns)

app/urls.py
from django.conf.urls import url
from app import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/login/$', views.login_user, name='login_user'),

    url(r'^signup/$', views.CreateUser.as_view(), name='sign_up'),

    url(r'^user/(?P<pk>[0-9]+)/$', views.view_user_id, name='profile'),

    url(r'^profile/(?P<user_id>[a-zA_Z0-9]+)/$', views.view_user_name, name='user-profile'),
    url(r'^user/dashboard/$', views.dashboard, name='dashboard'),
    url(r'^user/dashboard/messages/$', views.messages, name='dashboard_messages'),
    url(r'^user/dashboard/notifications/$', views.notifications, name='dashboard_notifications'),

    url(r'^accounts/profile/$', views.create_profile, name='profile_make'),


    url(r'^user/dashboard/sent/$', views.sent, name='dashboard_sent'),

    url(r'^user/dashboard/junk/$', views.messages_junk, name='dashboard_junk'),
    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/read/$', views.messages_read, name='dashboard_messages_read'),
    url(r'^user/dashboard/sent/(?P<message_id>[0-9]+)/read/$', views.messages_read_sent, name='dashboard_messages_read_sent'),

    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/reply/$', views.messages_reply, name='dashboard_messages_reply'),

    url(r'^user/dashboard/messages/(?P<message_id>[0-9]+)/forward/$', views.messages_forward, name='dashboard_messages_forward'),

    url(r'^user/dashboard/messages/compose/$', views.messages_compose, name='dashboard_messages_compose'),


    url(r'^accounts/login/$', views.login_user, name='login_user'),
    url(r'^terms/$', views.terms, name='terms'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^ride/(?P<user_id>[0-9]+)/$', views.ride, name='ride'),
    url(r'^ride/$', views.ride, name='ride'),

    url(r'^follow/(?P<followee>[0-9]+)/(?P<follower>[0-9]+)/$',views.do_follow,name='follow'),

    url(r'^user/(?P<pk>[0-9]+)/update-profile/$', views.EditUser.as_view(), name='user_update'),

    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^login/$', views.do_login, name='login'),



    url(r'^user/(?P<user_id>[0-9]+)/add-ride/$', views.vehicle_create, name='add_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/view-rides/$', views.vehicle_view, name='view_rides'),

    url(r'^user/(?P<user_id>[0-9]+)/delete-ride/(?P<vehicle_id>[0-9]+)/$', views.vehicle_delete, name='delete_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/share-ride/(?P<vehicle_id>[0-9]+)/$', views.vehicle_share, name='share_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/view-shared/$', views.vehicle_shared_view, name='view_shared'),

    url(r'^user/(?P<user_id>[0-9]+)/search/$', views.vehicle_search, name='search_ride'),

    url(r'^user/(?P<user_id>[0-9]+)/request/(?P<ride_id>[0-9]+)', views.request_ride, name='request_ride'),

    url(r'^sharing/(?P<vehicle_share_id>[0-9]+)/view/$', views.view_single_ride, name='view_shared_ride'),

    url(r'^ride/(?P<ride_id>[0-9]+)/view/$', views.view_single_vehicle, name='view_shared_vehicle'),

    url(r'^sharing/(?P<user_id>[0-9]+)/delete/(?P<vehicle_share_id>[0-9]+)/$', views.vehicle_share_delete, name='delete_shared_ride'),

    url(r'^requests/(?P<user_id>[0-9]+)/view$', views.requests_driver_view, name='request_driver_view'),
    url(r'^requests/all$',views.all_ride_requests, name='view_ride_requests'),
    url(r'^request/(?P<request_id>[0-9]+)/approve/$', views.request_approve, name='request_driver_approve'),
    url(r'^request/(?P<request_id>[0-9]+)/deny/$', views.request_deny, name='request_driver_deny'),

    # url(r'^requests/(?P<user_id>[0-9]+)/view$', views.requests_driver_view, name='request_driver_view'),

    url(r'^request/(?P<request_id>[0-9]+)/view/$', views.request_view, name='request_view'),

    url(r'^user/(?P<user_id>[0-9]+)/requests/$', views.requests_user_view, name='requests_user_view'),

    url(r'^request/(?P<request_id>[0-9]+)/delete/$', views.request_delete, name='request_delete'),

    url(r'^notification/read/$', views.mark_as_read, name='mark_as_read'),

    url(r'^user/messages/unread/$', views.unread_messages, name='unread_messages'),
    url(r'^user/messages/(?P<message_id>[0-9]+)/delete/$', views.delete_message, name='delete_message'),

    url(r'^user/preferences/$', views.preferences, name='preferences'),

     url(r'^user/preferences/image-update$', views.image_update, name='image_update'),

    url(r'^user/preferences/basic-update$', views.basic_update, name='basic_update'),
    url(r'^user/preferences/user-update$', views.user_update, name='user_update'),
    url(r'^user/preferences/driver-update$', views.driver_update, name='driver_update'),
    url(r'^user/preferences/bio-update$', views.bio_update, name='bio_update'),
    url(r'^user/preferences/app-update$', views.app_update, name='app_update'),
    url(r'^user/preferences/social-update$', views.social_update, name='social_update'),
    url(r'^user/preferences/password-update$', views.password_update, name='password_update'),




]

broadcast/urls.py
from django.conf.urls import include, url
from broadcast import views

app_name = 'broadcast'
urlpatterns = [
    url(r'^upload/text/$', views.upload_text, name='upload_text'),
    url(r'^upload/image/$', views.upload_image, name='upload_image'),
    url(r'^upload/ride/$', views.upload_ride, name='upload_ride'),
    url(r'^upload/direction/$', views.upload_direction, name='upload_direction'),
    url(r'^$',views.index,name='index'),
    url(r'^like/(?P<broadcast_id>[0-9]+)/$', views.like_broadcast, name='like_broadcast'),
    url(r'^rebc/(?P<bc_id>[0-9]+)/$', views.rebc, name='rebc'),
    url(r'^(?P<bc_id>[0-9]+)/view/$', views.broadcast_view, name='view'),
    url(r'^comment/(?P<broadcast_id>[0-9]+)/$', views.comment, name='comment'),

]

app/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils.translation import ugettext_lazy as _
from django.forms import widgets
from .models import *


class CustomUserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    username = forms.RegexField(label=_("Username (all lowercase)"), min_length=5, max_length=30,
                                regex=r'^[\a-z.@+-]+$',
                                help_text=_("Required. 5-30 lowercase characters. Letters, digits and "
                                            "@/./+/-/_ only."),
                                error_messages={
                                    'invalid': _("This value may contain only 5-30 lower case letters, numbers and "
                                                 "@/./+/-/_ characters.")})

    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput,
                                help_text=_("Enter the same password as above, for verification."))

    gender = forms.ChoiceField(choices=(('Male', 'Male'), ('Female', 'Female')))

    user_type = forms.ChoiceField(choices=(('Pilot', 'Pilot'), ('Passenger', 'Passenger')))


    class Meta:
        # Point to our CustomUser here instead of default `User`
        model = CustomUser
        fields = ('full_name', 'short_name', 'email', 'gender', 'phone_number', 'user_type', 'address', 'username')

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.

        username = self.cleaned_data["username"]
        username = username.lower()
        try:
            # Refer to our CustomUser here instead of default `User`
            CustomUser._default_manager.get(username=username)
        except CustomUser.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        # Make sure we pass back in our CustomUserCreationForm and not the
        # default `UserCreationForm`
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class CustomUserChangeForm(forms.ModelForm):
    username = forms.RegexField(
        label=_("Username"), max_length=30, regex=r"^[\w.@+-]+$",
        help_text=_("Required. 30 characters or fewer. Letters, digits and "
                    "@/./+/-/_ only."),
        error_messages={
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password = ReadOnlyPasswordHashField(label=_("Password"),
                                         help_text=_("Raw passwords are not stored, so there is no way to see "
                                                     "this user's password, but you can change the password "
                                                     "using <a href=\"password/\">this form</a>."))

    class Meta:
        # Point to our CustomUser here instead of default `User`

        model = CustomUser
        fields = (
        'full_name', 'short_name', 'email', 'sex', 'phone_number', 'user_type', 'address', 'username', 'password')

    def __init__(self, *args, **kwargs):
        # Make sure we pass back in our CustomUserChangeForm and not the
        # default `UserChangeForm`
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class VehicleAddForm(forms.ModelForm):
    year = forms.IntegerField(widget=forms.TextInput(attrs={'type':'number','class': 'form-control', 'required':True}))
    make = forms.CharField(widget=forms.TextInput(attrs={'required': True,'class':'form-control'}))
    model = forms.CharField(widget=forms.TextInput(attrs={'required': True,'class':'form-control'}))

    type = forms.ChoiceField(choices=(('private', 'private'), ('hired', 'hired')),
                             widget=forms.Select(attrs={'class': 'form-control', 'required': True}))
    seats = forms.IntegerField(widget=forms.TextInput(attrs={'type':'number','class': 'form-control', 'required':True}))


    category = forms.ChoiceField(choices=(('Car', 'Car'), ('Bus', 'Bus'),
                                          ('Coaster', 'Coaster'), ('Truck', 'Truck')),
                                 widget=forms.Select(attrs={'class': 'form-control', 'required': True}))

    class Meta:
        model = Vehicle
        fields = ['year', 'make', 'model','plate', 'seats', 'type', 'category']


class VehicleShare(forms.ModelForm):
    date = forms.DateField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'required': True,'data-date-start-date':'0d', 'readonly':True}))
    start_time = forms.TimeField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, 'readonly':True}))
    arrival_time = forms.TimeField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, 'readonly':True}))
    start = forms.CharField(widget=forms.TextInput(attrs={'required': True,'class':'form-control'}))
    dest = forms.CharField(widget=forms.TextInput(attrs={'required': True,'class':'form-control'}))
    pickuppoint = forms.CharField(widget=forms.TextInput(attrs={'required': True,'class':'form-control'}))  
    details = forms.CharField(widget=forms.Textarea(attrs={'required': True,'class':'form-control'}))
    details.label = 'Ride Details'
    choices = (('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both'))
    sex = forms.ChoiceField(choices=choices,widget=forms.Select(attrs={'required': True,'class':'form-control'}))
    sex.label= 'Gender Preference'
    start.label ='Starting Point'
    dest.label = 'Desination'
    pickuppoint.label = 'Pickup Point'


    class Meta:
        model = VehicleSharing
        fields = ['start', 'dest','pickuppoint','cost', 'date', 'start_time', 'arrival_time', 'no_pass','details', 'sex']

    def __init__(self, *args, **kwargs):
        super(VehicleShare, self).__init__(*args, **kwargs)


class RequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ['pick', 'dest', 'bearable']

app/templates/app/user/driver_template.html
<ul class="navigation">
                                            <li>
                                                <a href="{% url 'app:index' %}">Home</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'app:user_update' request.user.id %}">Edit Profile</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'app:add_ride' request.user.id %}">Add Ride</a>
                                            </li>

                                            <li>
                                                <a href="{% url 'app:view_rides' request.user.id %}">View/Share Rides</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'app:view_shared' request.user.id %}">View Shared Rides</a>
                                            </li>
                                        </ul>

app/templates/app/user/edit_profile.html
{% extends 'app/user/user_template.html' %}
{% block username %}{{  request.user.username}}{% endblock %}
{% block messages %}
    {% if request.user.get_no_messages > 0 %}
        {{ request.user.get_no_messages }}
    {% endif %}
{% endblock %}
{% block notifications%}
    {% if request.user.get_no_notifs > 0 %}
        {{ request.user.get_no_notifs }}
    {% endif %}
{% endblock %}

{% block navigation %}
    {% if request.user.user_type == 'Driver' %}
        {% include 'app/user/driver_template.html' %}
    {% elif request.user.user_type == 'Passenger' %}
        {% include 'app/user/passenger_template.html' %}
    {% endif %}

{% endblock %}

{% block user_notifications %}
    {% for notif in request.user.get_notifications %}
        <li>
            <a href="" class="ride-content">
                {{ notif.level }} - {{ notif.description }} &nbsp;<h6>{{ notif.timestamp|timesince  }}&nbsp;ago</h6>
            </a>

        </li>
    {% endfor %}
{% endblock %}

{% block user_messages %}

    {% for message in request.user.get_messages %}
        <li>
            <a href="" class="ride-content">
                {{ message.message|truncatechars:30 }}  from <h6>{{ message.sender }}</h6>
            </a>

        </li>
    {% endfor %}

{% endblock %}

{% block body %}
{% if request.user.id == user.id %}
    {% include 'app/user/edit_profile_main.html' %}
{% else %}
    <section class="main-content">
        <h1 class="alert-danger alert text-center">FORBIDDEN</h1>

    </section>
{% endif %}

{% endblock %}

app/templates/app/user/header_driver.html
{% load static %}
<header class="main-header">
    <nav class="navbar navbar-static-top " >
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'app:index' %}" class="navbar-brand"
                   style="
    padding-left: 30px;
    padding-top: 0px;
    padding-bottom: 0px;
">   <img class="hidden-sm hidden-xs" src="{% static 'app/img/mylogo.png' %}"/>
       <img class="visible-sm visible-xs " height="30" style="margin-top: 10px" src="{% static 'app/img/mylogo.png' %}"

                />
                    </a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'app:dashboard' %}"><i class="fa fa-dashboard"></i>&nbsp;Dashboard<span class="sr-only">(current)</span></a></li>
                    <li><a href="{% url 'broadcast:index' %}"><i class="fa fa-bullhorn"></i>&nbsp;Broadcasts</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-road"></i>&nbsp;Actions <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'app:add_ride' request.user.id %}">Add Ride</a></li>
                            <li><a href="{% url 'app:view_rides' request.user.id %}">View / Share Ride</a></li>
                            <li><a href="{% url 'app:view_shared' request.user.id %}">View Shared Rides</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'app:search_ride' request.user.id %}">Search Ride</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'app:requests_user_view' request.user.id %}">View Requested Rides</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
                    </div>
                </form>
            </div>
            <!-- /.navbar-collapse -->
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->
                    <li class="dropdown messages-menu">
                        <!-- Menu toggle button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-envelope-o"></i>
                            <span class="label label-success" id="msg_badge"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have <span id="msg_no"></span> new
                                messages

                            </li>
                            <li>
                                <!-- inner menu: contains the messages -->
                                <ul class="menu" id="msg-menu">



                                    <!-- end message -->
                                </ul>
                                <!-- /.menu -->
                            </li>
                            <li class="footer"><a href="{% url 'app:dashboard_messages' %}">See All Messages</a></li>
                        </ul>
                    </li>
                    <!-- /.messages-menu -->

                    <!-- Notifications Menu -->
                    <li class="dropdown notifications-menu">
                        <!-- Menu toggle button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning"> <span id='live_notify_badge'></span> </span>
                        </a>

                        <ul class="dropdown-menu">
                            <li class="header">You have <span id='live_notify_badge2'></span> new
                                notifications
                            </li>

                            <li>

                                <!-- Inner Menu: contains the notifications -->
                                <ul class="menu" id="live_notify_list">
                                    <!-- end notification -->
                                </ul>
                            </li>
                            <li class="footer"><a href="{% url 'app:dashboard_notifications' %}">View all</a></li>
                        </ul>
                    </li>

                    <!-- Tasks Menu -->
                    <li class="dropdown tasks-menu">
                        <!-- Menu Toggle Button -->
                        <a href="{% url 'app:preferences' %}">
                            <i class="glyphicon glyphicon-cog"></i>
                        </a>
                    </li>
                    <!-- User Account Menu -->
                    <li class="dropdown user user-menu">
                        <!-- Menu Toggle Button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <!-- The user image in the navbar-->
                            <img src="{{ request.user.get_profile.picture.url }}" class="user-image" alt="User Image">
                            <!-- hidden-xs hides the username on small devices so only the image appears. -->
                            <span class="hidden-xs">{{ request.user.full_name|default:'Profile' }}
                            {% if user.is_verified %}<i class="fa fa-check btn-primary img-circle"></i>{% endif %}

                            </span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- The user image in the menu -->
                            <li class="user-header">
                                <img src="{{ request.user.get_profile.picture.url }}" class="img-circle" alt="User Image">

                                <p>
                                    {{ request.user.full_name }} - {{ request.user.user_type }}
                                    {% if request.user.is_verified %}<i class="fa fa-check btn-primary img-circle"></i>{% endif %}


                                    <small>Member since {{ request.user.date_joined|date }}</small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body">
                                <div class="row">
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Followers</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Sales</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Following</a>
                                    </div>
                                </div>
                                <!-- /.row -->
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{{ request.user.get_absolute_url }}" class="btn btn-default btn-flat">Profile</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'app:logout_user' %}" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-custom-menu -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</header>

app/templates/app/user/passenger_template.html
                                        <ul class="navigation">
                                            <li>
                                                <a href="{% url 'app:index' %}">Home</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'app:user_update' request.user.id %}">Edit Profile</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'app:search_ride' request.user.id %}">Search Vehicle</a>
                                            </li>

                                            <li>
                                                <a href="{% url 'app:requests_user_view' request.user.id %}">View Requested Vehicles</a>
                                            </li>
                                        </ul>

app/templates/app/user/user_form.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Car Port</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{% static "app/bootstrap/css/bootstrap.min.css" %}">
    <!-- Font Awesome -->
    <!-- Ionicons -->
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "app/dist/css/AdminLTE.min.css" %}">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="{% static "app/dist/css/skins/app-skin.css" %}">

    <!-- Modernizr -->


    <!-- Fonts -->
    <link type="text/css" href={% static 'app/css/font-awesome.min.css' %} rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<style>
    .login-page, .register-page{
        background: transparent;
    }
    #logo-text{
        color: white;
    }
    html{

        background: url({% static 'app/img/registerPic.jpg' %}) no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
</style>

<body class="hold-transition register-page">
<div class="register-box">
    <div class="register-logo">
        <a href="/" id="logo-text"><i class="fa fa-car"></i>&nbsp;<b>Car</b>port</a>
    </div>

    <div class="register-box-body">
        <p class="login-box-msg">Just a few more steps</p>


        <form action="" autocomplete="on" role="form" method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {% include 'app/template_form.html' %}
            <p>By signing up, you agree to the <a href="{% url 'app:terms' %}">Terms of Service</a> and <a href="{% url 'app:terms' %}">Privacy Policy</a>
                .Others will be able to find you by email or by phone when provided.
            </p>
            <div class="col-xs-offset-8 col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
            </div>

        </form>

        <!-- <div class="social-auth-links text-center">
            <p>- OR -</p>
            <a href="https://myride.auth0.com/authorize?response_type=code&scope=openid%20profile&client_id=Li1h8im1PjLRuZUl6JlUSYrRodwAabsQ&redirect_uri=http://localhost:8000/api/login/&connection=facebook"
               class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using
                Facebook</a>
        </div> -->


        <a href="{% url 'app:login' %}" class="text-center">I already have a membership</a>
    </div>
    <!-- /.form-box -->
</div>
<!-- /.register-box -->

<script>


</script>
<!-- jQuery 2.2.3 -->
<script src="{% static "app/plugins/jQuery/jquery-2.2.3.min.js" %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static "app/bootstrap/js/bootstrap.min.js" %}"></script>


</body>